# Generated by Django 4.2.14 on 2024-07-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
